@url = http://localhost:5001

###
POST {{url}}/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email" : "chukunwaoghor@gmail.com",
    "password" : "test12345"
}

###
POST {{url}}/api/user/register HTTP/1.1
Content-Type: application/json

{
    "firstName" : "test0004",
    "lastName" : "test",
    "email" : "chukunwaoghor@gmail.com",
    "password" : "test12345"
}

###
GET {{url}}/user/confirm/41942069-cdc5-42be-9f7c-57201cbbb2be HTTP/1.1